README.md

Implementation of issue https://github.com/fabric8-analytics/f8a-stacks-report/issues/12

Info about tooling

---

runtests.sh

Fix for the issue https://github.com/fabric8-analytics/f8a-stacks-report/issues/17

Improved runtests.sh script

---

check-docstyle.sh
cico_run_pydoc.sh
cico_run_pylint.sh
detect-common-errors.sh
detect-dead-code.sh
measure-cyclomatic-complexity.sh
measure-maintainability-index.sh
run-linter.sh
runtests.sh
tools/check_python_version.py

Implements https://github.com/fabric8-analytics/f8a-stacks-report/issues/55

Check Python version on CI

---

tests/test_stack_report_helper.py

Issue Ref: https://github.com/fabric8-analytics/f8a-stacks-report/issues/66

Fixing Test case

---

openshift/template.yaml

Reverts fabric8-analytics/f8a-stacks-report#91

Revert "[TEST]change cron schedule"

---

f8a_report/report_helper.py

[WIP] emr api log added

---

f8a_report/report_helper.py

added logs to view bucket names

bucket name logs added

---

f8a_report/report_helper.py
f8a_report/s3_helper.py

- corrected maven aws_id in s3_helper
- added logs to understand errors

[WIP] Mvn aws id fixed 3

---

openshift/template.yaml

this PR is created to be merged after 'saas-analytics' staging memory is increased(and merged) to 2048-2048.

changing memory to 1024-2048

---

openshift/template.yaml

please don't merge this PR, it needs to be merged after Sas-analytics PR is merged

schedule change to daily 12 midnight

---

f8a_report/main.py
f8a_report/report_helper.py
tests/test_main.py
tests/test_stack_report_helper.py

- 'weekly retraining' functioning
- 'collated-monthly.json' getting created
- separate functions for 'retraning' and 'create venus report' created
- tested on dev cluster

Weekly retraining correction v5

---

f8a_report/manifest_helper.py

Fixes
```
Traceback (most recent call last):
--
with open(file_path, 'w') as manifest:
PermissionError: [Errno 13] Permission denied: '/f8a_report/f8a_report/manifests/npmlist.json'
```

Permission error

---

f8a_report/graph_report_generator.py
f8a_report/main.py
f8a_report/manifest_helper.py
f8a_report/report_helper.py

Logging Message are real blessing for debuging and error tracing.

 Logging info messages added

---

f8a_report/manifest_helper.py
f8a_report/s3_helper.py
openshift/template.yaml
qa/runtests.sh
tests/test_manifest_helper.py
tests/test_s3_helper.py

Bucket name updated in reference to https://jira.coreos.com/browse/APPSRE-1223

bucket name update

---

f8a_report/main.py

Reverts fabric8-analytics/f8a-stacks-report#134

Revert "triggering manifest generation"

---

f8a_report/main.py
openshift/template.yaml
qa/runtests.sh

variables as string

---

README.md

trigger e2e

---

f8a_report/main.py

As for testing purpose on staging, need to change the schedule from every monday to daily.

Change the schedule from every monday to daily

---

f8a_report/main.py

As NPM retraining is working fine on Staging, so need to revert the schedule again to weekly.

Revert the schedule for retraining.

---

f8a_report/main.py
qa/runtests.sh
tests/test_main.py

- Wrapped `retraining` in Try Catch.
- Temporarily Trigger Generating Manifests Daily.
- Added Logging Parameters.

Encapsulated retraining in try except.

---

f8a_report/main.py

- Reverting Manifest Generation to weekly Ref https://github.com/fabric8-analytics/f8a-stacks-report/pull/145
- Adding Log Statements

Reverting Manifest Generation to weekly

---

f8a_report/main.py

Reverts fabric8-analytics/f8a-stacks-report#150
Resuming Manifest Generation to weekly

Revert "reverting Manifest Generation to daily"

---

f8a_report/sentry_report_helper.py

Dummy changes to trigger CI and update new env-var from saas-template.

Dummy changes to trigger CI and update new env-var from saas-template.

---

f8a_report/report_helper.py
qa/check-bashscripts.sh
requirements.in
requirements.txt
tests/test_unknown_deps_report_helper.py

There are format changes in V2 Stack Analyse API.
This PR has Venus Report changes in accordance to make existing implementation Unbreakable.

venus report changes wrt v2 API changes

---

f8a_report/main.py
f8a_report/unknown_deps_report_helper.py
f8a_report/v2/db_gateway.py
f8a_report/v2/report_generator.py
tests/data/normalised_ingestion_data.json
tests/data/normalised_worker_data.json
tests/data/report_summary.json
tests/data/stack_report_v2.json
tests/data/unknown_dependencies.json
tests/test_main.py
tests/v2/test_db_gateway.py
tests/v2/test_report_generator.py

Feature Addition: Added Venus Report Support for Stack Analyses V2 API.
Please find Sample Test Reports here
https://s3.console.aws.amazon.com/s3/buckets/deepshar-developer-analytics-audit-report/v2/?region=us-east-1&tab=overview

venus report: support for Stack Analyses v2 format.

---

f8a_report/v2/report_generator.py
tests/v2/test_report_generator.py

Fix key Error occured due to changes in v2 format.

fixed cve data read issue

---

f8a_report/v2/report_generator.py
tests/v2/test_report_generator.py

Bugfix for Report v2:  missing package details of Unknown Dependencies listing. 
Please find Full Report at https://s3.console.aws.amazon.com/s3/object/stage-developer-analytics-audit-report/v2/daily/2020-06-14.json?region=us-east-1&tab=overview

fix: Unknown dependencies package name wont show up.

---

f8a_report/main.py
f8a_report/sentry_report_helper.py

Exception handling in Daily Report.
Exception Raised by one report will not affect other Reports Generation

Exception handling in daily reports

---

README.md

Changing README (#168)

---

f8a_report/helpers/report_helper.py
f8a_report/helpers/unknown_deps_report_helper.py
f8a_report/v2/report_generator.py
tests/data/normalised_worker_data_with_golang.json
tests/helpers/test_stack_report_helper.py
tests/v2/test_report_generator.py

Golang Venus Reporting
Jira: https://issues.redhat.com/browse/APPAI-1584 

golang venus reporting

---

f8a_report/helpers/report_helper.py
openshift/template.yaml

This pr adds code to clean up recommendation_feedback table to support clean up to stack_analyses_requests table.
signed off by rmollah@redhat.com

fix: Add clean up of `recommendation_feedback` table. 

---

f8a_report/helpers/report_helper.py
openshift/template.yaml

Updated the clean up of package_worker_results table to use foreign key for clean up.This will make sure we clean same records for package_analyses table as well.

fix: Cean up of `package_analyses` table.

---

f8a_report/v2/report_generator.py

These PR adds Logging of variable state at the time of Exception.

varible state logging added

---

f8a_report/v2/report_generator.py
tests/v2/test_report_generator.py

Stack Report v2 has CVE ID, which is not unique and also Empty for Private Vulnerabilities.
This fix replaces CVEID in the report with Snyk ID
Jira: https://issues.redhat.com/browse/APPAI-1665

fix: Update Stack Report v2 to have Snyk Id

---

f8a_report/helpers/db_gateway.py
f8a_report/helpers/ingestion_helper.py
f8a_report/helpers/sentry_report_helper.py
f8a_report/stack_report_main.py
f8a_report/v2/report_generator.py
tests/test_main.py
tests/v2/test_report_generator.py

Turning V1 Venus Reporting OFF
- Move Sentry Reporting  out to the main function
- Move Ingestion Reporting out to the main function.

chore: turn v1 reporting off

---

Dockerfile
Dockerfile.new
Dockerfile.rhel
MAINTAINERS
f8a_report/dbtable_cleanup_main.py
f8a_report/helpers/cve_helper.py
f8a_report/helpers/db_gateway.py
f8a_report/helpers/ingestion_helper.py
f8a_report/helpers/manifest_helper.py
f8a_report/helpers/report_helper.py
f8a_report/helpers/sentry_report_helper.py
f8a_report/helpers/unknown_deps_report_helper.py
f8a_report/manifest_main.py
f8a_report/monthly_stack_report_main.py
f8a_report/retrain_main.py
f8a_report/snyk_token_validation_main.py
f8a_report/stack_report_main.py
f8a_report/v2/report_generator.py
tests/helpers/test_db_gateway.py
tests/test_main.py

Relative Imports are not understood by IDE's and the correct importing of custom Modules was kind of shooting in a dark.

chore: Update package imports to absolute

---

f8a_report/v2/report_generator.py
tests/helpers/test_s3_helper.py
tests/v2/test_report_generator.py

Removing Individual `stack_details` from Daily Venus Reporting
Part of  [Platform improvements to remove unnecessary costs](https://issues.redhat.com/browse/APPAI-1421)

chore: removing stack_details from daily venus reports

---

openshift/template.yaml

signed off by msawood@redhat.com

fix: Add timeout for the corn-job
